services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../*'
        exclude: '../../{Controller,DataFixtures,DependencyInjection,Entity,Repository}'